### PR TITLE
Fix intendation after nc line break

### LINKED ISSUE #45: an indentation after coments and cycle calls
if you deliberately design the indentations so that you can collapse certain blocks and then use the "ISG-CNC: Format Code" function, these indentations will be discarded again. It would be nice if these indentations were created when this function is executed.
it would be helpful if after comments and after cycle calls an indentation is generated.

**Before executing the function:**

Format Code 1

**After executing the function:**

Format Code 2

### PR DESCRIPTION
**Pull request by andreas-hafner**
Fixes #45

### CODE REVIEW

**Comment by lukashettler-isg** [comment]
@georgulbrich-isg 
Do you see a problem with this change if we indent after every line break \. For me this seems very useful to better detect a multi line command.

**Comment by andreas-hafner** [comment]
Fixed merge conflict.

**Comment by andreas-hafner** [comment]
Hi @georgulbrich-isg,
do you have an idea until when you will be able to process the review and the pull request?

**Comment by gu1729** [comment]
Hi @andreas-hafner ,

when I tried the functionality three days ago I could not get it to work.
Tried it ago today, seems to work now.
Code is okay, functioniality is okay.

Since I have no clue about VSCode, plugins, packages etc. I cant say if everything is okay.

@lukashettler-isg or @jurekseverin-isg , what do you think?

Best regards, Georg

**Comment by lukashettler-isg** [comment]
@andreas-hafner 
I tried the following program and wondered why it doesnt work. Can you please test it and say if it works at you?

```
%test
N10 H10 = V.P.1 \
H20 = V.P.2

M30
```

**Comment by andreas-hafner** [comment]
> %test
> N10 H10 = V.P.1 \
> H20 = V.P.2
> 
> M30

Hello @lukashettler-isg,
It doesnt work if I use only one backslash and the next line is a normal nc line, like in your example. There is something wrong in my implementation it only works with two and more backslash lines. I will try to fix it. Thanks for testing and finding a bug :-)

best regards
Andreas

**Comment by lukashettler-isg** [comment]
> > %test
> > N10 H10 = V.P.1 
> > H20 = V.P.2
> > M30
> 
> Hello @lukashettler-isg, It doesnt work if I use only one backslash and the next line is a normal nc line, like in your example. There is something wrong in my implementation it only works with two and more backslash lines. I will try to fix it. Thanks for testing and finding a bug :-)
> 
> best regards Andreas
> 
> @lukashettler-isg Edit: I fixed the problem. Now it works with one or more linebreaks. But it is not is not working with comments between linebreak lines like because i have to check the line before the current line:
> 
> %test N10 H10 = V.P.1 ; here is an not working comment H20 = V.P.2 H21 = V.P.3
> 
> M30

@andreas-hafner 

Thank you for improving the functionality. I can also reproduce the problem you mentioned with the following program.

```
%test
;N10 H10 = V.P.1 \
;H20 = V.P.2 \
H20 = V.P.2 \
  H20 = V.P.2 \
;122
H20 =V.P.3 \
  H20

M30
```

I also detect another unexpected behaviour with this program:

```
%test
;N10 H10 = V.P.1 \
;H20 = V.P.2 \
H20 = V.P.2 \
H20 = V.P.2

M30
```

The result is:
```
%test
;N10 H10 = V.P.1 \
;H20 = V.P.2 \
  H20 = V.P.2 \
  H20 = V.P.2

M30
```

**Comment by andreas-hafner** [comment]
Hello @lukashettler-isg,
```
%test
;N10 H10 = V.P.1 \
;H20 = V.P.2 \
H20 = V.P.2 \
H20 = V.P.2

M30

```
that works now. 
But the big question is what should happens with comments. If you want to allow comments between linebreaks? Then there should be a method to scan backward to the next valid nc line that isn't an comment to check the correct line break.
Is this a good idea to allow using comments between linebreaks, I think that makes it more complicat.

**Comment by gu1729** [comment]
Hello @andreas-hafner ,

with regards to the big question: we started to use a formal grammer for our CNC syntax. @jurekseverin-isg prepared it and as it produces an out-of-the-box parser we use it for detecting tool changes, cycle calls etc. There is also a long term strategy for using the grammar for more advanced features, but this will take some time.

The grammar is rather basic at the moment and does not cover the whole CNC syntax, but it can easily be expanded one step at a time. One of the grammars advantages is that it can handle comments properly. Maybe we can think about migrating the code format feature to the grammar approach.

Best regards, Georg

**Comment by jurekseverin-isg** [comment]
[Branch 78](https://github.com/isg-stuttgart/vscode-isg-cnc/pull/78/) should solve that by using our grammar to detect the multilines and indent them correctly in our extension.

**Pull request closed without merging**
